name: alecbishop
favicon: null
layout_spectrum: 0.010301062604412436
typography_spectrum: 1
title: Alec Bishop Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#410000'
    - '#572629'
    - '#967677'
    - '#c3b4b2'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.45946024963632226
  rhythmicContrast: 0.5
purpose: []
